include:
  - booklore/docker-compose.yaml
  - flaresolver-compose.yaml
  - prowlarr-compose.yaml
  - radarr-compose.yaml
  - sonarr-compose.yaml
  - audiobookshelf-compose.yaml
  - qbittorrent-compose.yaml
  - recyclarr/recyclarr-compose.yaml
  - shelfmark-compose.yaml
  - jellyfin-compose.yaml

networks:
  media:
  media-backend:
