include:
  - vaultwarden-compose.yaml
  - backrest-compose.yaml
  - sftpgo-compose.yaml
  - homebox-compose.yaml
  - n8n-compose.yaml
  - db-backup-compose.yaml
  - ownfoil-compose.yaml

networks:
  tools:
